name: waflo_admin
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

#------------------PACKAGES-------------------
dependencies:
  flutter:
    sdk: flutter


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # Utility Packages
  intl: ^0.18.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  flutter_dropzone: ^3.0.7
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^5.0.1
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  logger: ^2.3.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  
  # Firebase
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  firebase_storage: ^11.5.1
  google_sign_in: ^6.1.6

  # Web specific
  web: ^0.5.1
  http: ^1.1.2
  html: ^0.15.4
  fl_chart: ^0.66.2
  data_table_2: ^2.5.9
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true


#------------------LOCAL STORAGE-------------------
  assets:
    
    - assets/images/
    - assets/icons/
    - assets/logos/
    - google_fonts/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/products/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/